### ISSUE TITLE
User must also import the linkme crate

### ISSUE THREAD

**Issue by bddap** [bddap/bddap-aoc#6]
For bddap-aoc to work, user also needs to add the linkme crate to their Cargo.toml

```toml
[dependencies]
bddap-aoc = "0.1.1"
linkme = "0.3.17"
```

Ideally it would just be:

```toml
[dependencies]
bddap-aoc = "0.1.1"
```
